project_name: datadog-traceroute
builds:
  - id: traceroute
    main: ./traceroute.go
    binary: datadog-traceroute
    env: [CGO_ENABLED=0]
    goos:
      - linux
      #- windows
      #- darwin
    goarch:
      - amd64
      #- arm64
  - id: traceroute-server
    main: ./cmd/traceroute-server
    binary: datadog-traceroute-server
    env: [CGO_ENABLED=0]
    goos:
      - linux
      #- windows
      #- darwin
    goarch:
      - amd64
      #- arm64
nfpms:
- maintainer: Datadog
  description: Datadog Traceroute
  homepage: https://github.com/DataDog/datadog-traceroute
  license: Apache
  formats:
  - deb
  #- rpm
  #- apk
