project_name: datadog-traceroute
builds:
  - id: traceroute-linux
    main: ./traceroute.go
    binary: datadog-traceroute
    env: [CGO_ENABLED=0]
    ldflags:
      - -s -w
      - -X github.com/DataDog/datadog-traceroute/cmd.Version={{.Version}}
      - -X github.com/DataDog/datadog-traceroute/cmd.Commit={{.Commit}}
      - -X github.com/DataDog/datadog-traceroute/cmd.Date={{.Date}}
    goos:
      - linux
      #- darwin
    goarch:
      - amd64
      #- arm64
  - id: traceroute-windows
    main: ./traceroute.go
    binary: datadog-traceroute
    env:
      - CGO_ENABLED=1
      - CC=$CC_WINDOWS_AMD64
    ldflags:
      - -s -w
      - -X github.com/DataDog/datadog-traceroute/cmd.Version={{.Version}}
      - -X github.com/DataDog/datadog-traceroute/cmd.Commit={{.Commit}}
      - -X github.com/DataDog/datadog-traceroute/cmd.Date={{.Date}}
    goos:
      - windows
    goarch:
      - amd64
  - id: traceroute-server-linux
    main: ./cmd/traceroute-server
    binary: datadog-traceroute-server
    env: [CGO_ENABLED=0]
    goos:
      - linux
      #- darwin
    goarch:
      - amd64
      #- arm64
  - id: traceroute-server-windows
    main: ./cmd/traceroute-server
    binary: datadog-traceroute-server
    env:
      - CGO_ENABLED=1
      - CC=$CC_WINDOWS_AMD64
    goos:
      - windows
    goarch:
      - amd64
nfpms:
- maintainer: Datadog
  description: Datadog Traceroute
  homepage: https://github.com/DataDog/datadog-traceroute
  license: Apache
  formats:
  - deb
  #- rpm
  #- apk
