name: build

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write # needed to write releases

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    env:
      GOTOOLCHAIN: local
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          fetch-depth: 0
      - uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5.6.0
        with:
          go-version-file: ".go-version"
      - name: Install cross-compilation tools
        run: sudo apt-get update && sudo apt-get install -y gcc-mingw-w64-x86-64
      - run: go mod tidy
      - run: go test -tags=test -v ./...
      - uses: goreleaser/goreleaser-action@e435ccd777264be153ace6237001ef4d979d3a7a # v6.4.0
        if: success() && startsWith(github.ref, 'refs/tags/')
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CC_WINDOWS_AMD64: x86_64-w64-mingw32-gcc
